### PR TITLE
Fix bugs in create form

### LINKED ISSUE #90: Call api for only 1 search item (Dishes)
If there are more than 1 ingredients, search api is called for all array items. Ideally, it should be called only once.

Refer create meal form. This issue is fixed there.

Image

### LINKED ISSUE #91: Remove button misbehaving in all forms
Steps to reproduce:

1. Open any form, let's say ingredients form
2. Add 3 preparations having different preparation types
3. Delete 2nd preparation.

Actual:
- Third preparation gets deleted

Expected:
- Second preparation to be deleted

Solution:
- Change key to something unique other than index.

Explanation:
- Because when we delete index 1 item, index 2's new index becomes 1.
- React thinks that since index 2 is not available anymore, index 2 must have been deleted.

### PR DESCRIPTION
**Pull request by Van-sh**

### CODE REVIEW

File: src/planner/dishes/createForm/index.tsx [hunk 1]
```diff
@@ -87,45 +82,48 @@ export default function CreateForm({ initialValues, isLoading, onClose, onCreate
...
-      }, 750),
-    [queryList],
+      const getIngredientsPromise = getIngredients(
+        { query: newQuery, page: 1 },
+        preferCachedValues,
+      );
+      searchControllerRef.current = getIngredientsPromise;
+
+      const { data, requestId } = await getIngredientsPromise;
+      console.log(`${newQuery}: ${requestId}`);
```
Comment (SakshiShreya) [inline src/planner/dishes/createForm/index.tsx]: Remove console.log

File: src/planner/dishes/createForm/index.tsx [hunk 2]
```diff
@@ -184,8 +177,8 @@ export default function CreateForm({ initialValues, isLoading, onClose, onCreate
           <FieldArray name="ingredients">
             {({ push, remove }) => (
               <>
-                {formik.values.ingredients.map((_, index) => (
-                  <div key={index} className="bg-gray-100 flex flex-col gap-2 p-2 rounded-lg">
+                {formik.values.ingredients.map(({ ingredient: { _id } }, index) => (
```
Comment (SakshiShreya) [inline src/planner/dishes/createForm/index.tsx:179]: If we click on Add Ingredient, it will not have an _id.
If we click on Add Ingredient multiple times, it will create multiple new objects with duplicate key: `undefined`.

**Review by SakshiShreya — CHANGES_REQUESTED** [review]

File: src/planner/dishes/createForm/index.tsx (hunk 2 above)
Comment (SakshiShreya) [reply src/planner/dishes/createForm/index.tsx:179]: We have discussed this in #80. Resolving this.

**Comment by SakshiShreya** [comment]
@Van-sh There is a conflict. Please resolve.
Otherwise, good to go.

**Review by SakshiShreya — APPROVED** [review]
