### PR TITLE
103 and 105: Fix bugs

### LINKED ISSUE #103: Fix Meal Plan Card Size
- [ ] Fix this UI
Image

Keep adding more here

### LINKED ISSUE #105: Mobile view bugs
- Ingredients and Dishes Cards don't have keys
- ~~Dishes and Meals cards crash~~ (nevermind, my local data is bad)

### PR DESCRIPTION
**Pull request by SakshiShreya**
All columns are independently scrollable.

image

### CODE REVIEW

File: src/planner/ingredients/cards.tsx [hunk 1]
```diff
@@ -13,7 +13,7 @@ export default function IngredientCards({ data, onEdit, onDelete }: Props) {
   return (
     <>
       {data.map((ingredient) => (
-        <Card className="mt-4">
+        <Card className="mt-4" key={ingredient._id}>
```
Comment (Van-sh) [inline src/planner/ingredients/cards.tsx:16]: this needs to be done for dishes as well

File: src/planner/plans/edit/desktopView.tsx [hunk 2]
```diff
@@ -30,8 +30,10 @@ export default function DesktopView({ openCreatePlanModal }: Props) {
               Add Meal
             </Button>
           </div>
-          <Divider className="my-2" />
+          <Divider className="mt-2" />
+          <div className="w-full overflow-y-auto p-2">
           <MealCards day={day} />
```
Comment (Van-sh) [inline src/planner/plans/edit/desktopView.tsx]: run prettier through this

**Review by Van-sh — CHANGES_REQUESTED** [review]
two small things, rest looks good

File: src/planner/ingredients/cards.tsx (hunk 1 above)
Comment (Van-sh) [reply src/planner/ingredients/cards.tsx:16]: forgot to update the issue with this

Comment (SakshiShreya) [reply src/planner/ingredients/cards.tsx:16]: @Van-sh Done

File: src/planner/plans/edit/desktopView.tsx (hunk 2 above)
Comment (SakshiShreya) [reply src/planner/plans/edit/desktopView.tsx]: @Van-sh Done

**Review by Van-sh — APPROVED** [review]
